apiVersion: v1
data:
  domain: 104.198.131.172.nip.io
  email: ""
  exposer: Ingress
  issuer: ""
  tls: "false"
  urltemplate: ""
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ingress-config
